val sehir: String = "Kahramanmaras"
val ulke: String = "Turkiye"
val telefon: String = "05055554455"
val postaKodu: String = "46000"
val email: String = "email@email.com"
val meslek: String = "Bilgisayar Muhendisi"
val stokMiktari: Int = 100
val musteriAdi: String = "İrem Cingi"
val bakiye: Double = 4.75
val dogumGunu: String = "01-01-1990"
val maas: Double = 500.50
val medeniDurum: String = "Bekar"
val urunYorum: String = "Çok begendim!"
val odemeTarihi: String = "01-01-2024"
val odeme: Double = 50.0
val siparisAdeti: Int = 5
val arabaModeli: String = "Mercedes"
val kitapAdi: String = "Suc ve Ceza"
val yayinlamaTarihi: String = "1866"
val indirimMiktari: Double = 115.0
val odaSayisi: Int = 5
val enlem: Double = 26.0082
val boylam: Double = 42.0784
val urunAdi: String = "Laptop"
val yemekFiyati: Double = 175.0
val marka: String = "Dell"
val muzikAdi: String = "Imagine"
val videoSuresi: Int = 10
val urunPuani: Double = 4.5
val resimAdi: String = "windows.jpg"
val dosyaFormati: String = ".jpg"
val renk: String = "mavi"
val renkKodu: String = "#FFFFFF"
val telefonModeli: String = "Samsung A6"
val ekranBoyutu: Double = 6.1
val agirlik: Double = 0.174
val ulusalGun: String = "29 Ekim"
val tatilGunu: String = "Yılbaşı"
val rezervasyonTarihi: String = "12-01-2024"
val sokakAdi: String = "İstiklal Caddesi"
val otobusHatti: String = "38B"
val kalanDakika: Int = 10
val takipKodu: String = "ABC12345ABC"
val kuponSuresi: Int = 10
val kuponKodu: String = "KUPON100"
val faturaAdresi: String = "Kahramanmaras, Turkiye"
